<a href="https://colab.research.google.com/github/faruq2021/My-ML-MODEL-NOTEBOOKS/blob/main/SOLP_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk


In [2]:
Table={}
Table["Name"]=["ade","kunle","dayo","josh","elisha","joke","Ismail","Akeem","samuel","john","zulfah","tao","salam","simbi","hezek","Sanusi","kasal","munir","ramat","ike"]
Table["Avg_m_income"]=[800000,60000,50000,120000,30000,230000,500000,120000,80000,50000, 95000,600000,80000,1500000,280000,80000,400000,70000,210000,1000000]
Table["avg_daily_exp"]=[6000,2000,3000,4000,5000,4000,4000,6000,5000,6000,6000,3000,4000,2000,5000,4000,6000,3000,2000,6000]
Table["no_of_dep"]=[6,2,3,4,5,4,4,6,5,6,6,3,4,2,2,5,4,6,3,2]
Table["Classes"]=[1,3,3,3,3,2,1,3,3,3,3,1,3,1,1,3,1,3,2,1,]

In [3]:
Observation=pd.DataFrame(Table)

In [4]:
Observation.head()

Name  Avg_m_income  avg_daily_exp  no_of_dep  Classes
0     ade        800000           6000          6        1
1   kunle         60000           2000          2        3
2    dayo         50000           3000          3        3
3    josh        120000           4000          4        3
4  elisha         30000           5000          5        3

In [5]:
Observation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Name           20 non-null     object
 1   Avg_m_income   20 non-null     int64 
 2   avg_daily_exp  20 non-null     int64 
 3   no_of_dep      20 non-null     int64 
 4   Classes        20 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 928.0+ bytes


In [6]:
m_d=Observation[["Avg_m_income","avg_daily_exp","no_of_dep","Classes"]]

In [7]:
X=np.asarray(m_d[["Avg_m_income","avg_daily_exp","no_of_dep"]])
X[0:5]



array([[800000,   6000,      6],
       [ 60000,   2000,      2],
       [ 50000,   3000,      3],
       [120000,   4000,      4],
       [ 30000,   5000,      5]])

In [8]:
y=np.asarray(m_d[["Classes"]])
y[0:5]

array([[1],
       [3],
       [3],
       [3],
       [3]])

In [9]:
#data normaliziation
from sklearn import preprocessing 

X=preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.2691836 ,  1.19908755,  1.31425748],
       [-0.67834541, -1.62229492, -1.45260037],
       [-0.70466337, -0.9169493 , -0.76088591],
       [-0.52043765, -0.21160368, -0.06917145],
       [-0.75729929,  0.49374193,  0.62254302]])

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [11]:
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (16, 3) (16, 1)
Test set: (4, 3) (4, 1)


In [12]:
from sklearn.linear_model import LogisticRegression
LogRegModel=LogisticRegression(C=0.01,solver="liblinear").fit(X_train,y_train)
LogRegModel

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
prediction=LogRegModel.predict(X_test)

In [15]:
prediction

array([1, 1, 3, 3])

In [20]:
pred_prob = LogRegModel.predict_proba(X_test)
pred_prob

array([[0.35162471, 0.32984213, 0.31853316],
       [0.34887029, 0.33674816, 0.31438154],
       [0.33177616, 0.32307593, 0.34514792],
       [0.33060613, 0.32285908, 0.34653479]])

In [17]:
#evaluating model using jaccard_similarity
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, prediction)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


1.0